/**
 * Maps a technology label, as written in project and experience front matter,
 * to an icon key understood by src/components/home/SkillIcon.jsx. Unknown
 * technologies fall back to a plain chip glyph there. Labels are matched
 * case-insensitively with punctuation and spaces ignored.
 */
const ICONS = {
  python: "python",
  opencv: "opencv",
  numpy: "numpy",
  pandas: "pandas",
  ultralyticsyolo: "ultralytics",
  yolo: "ultralytics",
  customtkinter: "monitor",
  pyautogui: "mouse",
  pyinstaller: "package",
  react: "react",
  nextjs: "nextjs",
  nodejs: "nodejs",
  typescript: "typescript",
  tailwind: "tailwind",
  playwright: "test",
  docker: "docker",
  awss3: "cloud",
  "c++": "cpp",
  stm32: "stm",
  freertos: "timer",
  can: "network",
  touchgfx: "panel",
  powerbi: "chart",
  excel: "sheet",
  vba: "code",
  pytorch: "pytorch",
  vite: "vite",
  reactrouter: "reactrouter",
  chakraui: "chakra",
  cypress: "cypress",
  vercel: "vercel",
  postgresql: "postgres",
  kicad: "kicad",
  freecad: "freecad",
  huggingface: "huggingface",
  roboflow: "roboflow",
  circuitpython: "python",
  vitishls: "amd",
  vivado: "amd",
  artix7: "amd",
  rp2040: "raspberry",
  xiaorp2040: "raspberry",
  vhdl: "circuit",
  fpga: "cpu",
  basys3: "circuit",
  kriakv260: "cpu",
  pynq: "cpu",
  i2c: "cable",
  i2s: "audio",
  axi: "workflow",
  axi4stream: "waves",
  axidma: "workflow",
  ssd1306: "monitor",
  kmk: "keyboard",
  imagenet1k: "images",
  rtdetr: "scan",
  albumentations: "images",
  alexnet: "brain",
  resnet18: "brain",
  vgg19: "brain",
  supervision: "scan",
  erd: "database",
  relationalmodelling: "database",
  normalization: "database",
  gpio: "cable",
  interrupts: "timer",
  timers: "timer",
  lcd: "monitor",
  c: "code",
  os161: "memory",
  mips: "cpu",
  gdb: "bug",
};

const normalise = (label) => label.toLowerCase().replace(/[^a-z0-9+]/g, "");

/** Icon key for a technology label, or null when there is no mapping. */
export function techIcon(label) {
  return ICONS[normalise(label)] ?? null;
}
